// To parse this JSON data, do
//
//     final hoteldetailModel = hoteldetailModelFromJson(jsonString);

import 'dart:convert';

HoteldetailModel hoteldetailModelFromJson(String str) =>
    HoteldetailModel.fromJson(json.decode(str));

String hoteldetailModelToJson(HoteldetailModel data) =>
    json.encode(data.toJson());

class HoteldetailModel {
  dynamic bookingId;
  dynamic searchlogid;
  dynamic customerId;
  dynamic paymentapiId;
  String bookingCode;
  dynamic voucherCode;
  dynamic bookingConfirmationCode;
  dynamic commonId;
  bool bookingStatus;
  bool cancellationStatus;
  bool mailStatus;
  bool smsStatus;
  dynamic remark;
  dynamic bookingDate;
  dynamic noOfPax;
  dynamic totalCost;
  dynamic basicCost;
  dynamic profit;
  dynamic discount;
  dynamic dob;
  dynamic agentId;
  dynamic employeeId;
  dynamic employee;
  dynamic customerDto;
  dynamic hotelBookingDtoArray;
  dynamic emailId;
  dynamic mobileNumber;
  dynamic agentName;
  dynamic type;
  dynamic userId;
  dynamic employeeid;
  dynamic customerName;
  dynamic count;
  dynamic cancel;
  dynamic booking;
  dynamic hotelname;
  dynamic hoteltype;
  dynamic hotelid;
  dynamic hotelCategory;
  dynamic bookingdate;
  dynamic bookingTdy;
  List<HotelBookingDtoList> hotelBookingDtoList;
  dynamic hotelBookingDto;
  dynamic hotelBookingDtoRebook;
  dynamic companyName;
  dynamic address;
  dynamic mailId;
  dynamic telephone;
  dynamic website;
  dynamic firstName;
  dynamic middleName;
  dynamic lastName;
  dynamic age;
  dynamic nativeCountry;
  dynamic salutaion;
  dynamic passportNo;
  dynamic policyDetailsDtoList;
  dynamic bookingNew;
  dynamic hotelIdList;
  dynamic context;
  dynamic confirmationStatus;
  dynamic accessCode;
  dynamic client;
  dynamic clientrefernce;
  dynamic apiId;
  dynamic supplier;
  dynamic hotelreference;
  dynamic hotelName;
  dynamic createdBy;
  dynamic hotelId;
  dynamic pending;
  dynamic nativeCountryCode;
  dynamic packagebookingid;
  dynamic packageBookingCabDto;
  dynamic availableLimit;
  bool deleted;
  bool refund;
  bool rebooking;

  HoteldetailModel({
    required this.bookingId,
    required this.searchlogid,
    required this.customerId,
    required this.paymentapiId,
    required this.bookingCode,
    required this.voucherCode,
    required this.bookingConfirmationCode,
    required this.commonId,
    required this.bookingStatus,
    required this.cancellationStatus,
    required this.mailStatus,
    required this.smsStatus,
    required this.remark,
    required this.bookingDate,
    required this.noOfPax,
    required this.totalCost,
    required this.basicCost,
    required this.profit,
    required this.discount,
    required this.dob,
    required this.agentId,
    required this.employeeId,
    required this.employee,
    required this.customerDto,
    required this.hotelBookingDtoArray,
    required this.emailId,
    required this.mobileNumber,
    required this.agentName,
    required this.type,
    required this.userId,
    required this.employeeid,
    required this.customerName,
    required this.count,
    required this.cancel,
    required this.booking,
    required this.hotelname,
    required this.hoteltype,
    required this.hotelid,
    required this.hotelCategory,
    required this.bookingdate,
    required this.bookingTdy,
    required this.hotelBookingDtoList,
    required this.hotelBookingDto,
    required this.hotelBookingDtoRebook,
    required this.companyName,
    required this.address,
    required this.mailId,
    required this.telephone,
    required this.website,
    required this.firstName,
    required this.middleName,
    required this.lastName,
    required this.age,
    required this.nativeCountry,
    required this.salutaion,
    required this.passportNo,
    required this.policyDetailsDtoList,
    required this.bookingNew,
    required this.hotelIdList,
    required this.context,
    required this.confirmationStatus,
    required this.accessCode,
    required this.client,
    required this.clientrefernce,
    required this.apiId,
    required this.supplier,
    required this.hotelreference,
    required this.hotelName,
    required this.createdBy,
    required this.hotelId,
    required this.pending,
    required this.nativeCountryCode,
    required this.packagebookingid,
    required this.packageBookingCabDto,
    required this.availableLimit,
    required this.deleted,
    required this.refund,
    required this.rebooking,
  });

  factory HoteldetailModel.fromJson(Map<String, dynamic> json) =>
      HoteldetailModel(
        bookingId: json["booking_id"],
        searchlogid: json["searchlogid"],
        customerId: json["customer_id"],
        paymentapiId: json["paymentapi_id"],
        bookingCode: json["booking_code"],
        voucherCode: json["voucher_code"],
        bookingConfirmationCode: json["booking_confirmation_code"],
        commonId: json["common_id"],
        bookingStatus: json["booking_status"],
        cancellationStatus: json["cancellation_status"],
        mailStatus: json["mail_status"],
        smsStatus: json["sms_status"],
        remark: json["remark"],
        bookingDate: json["booking_date"],
        noOfPax: json["no_of_pax"],
        totalCost: json["total_cost"],
        basicCost: json["basic_cost"],
        profit: json["profit"],
        discount: json["discount"],
        dob: json["dob"],
        agentId: json["agent_id"],
        employeeId: json["employee_id"],
        employee: json["employee"],
        customerDto: json["customerDTO"],
        hotelBookingDtoArray: json["hotelBookingDTOArray"],
        emailId: json["emailId"],
        mobileNumber: json["mobileNumber"],
        agentName: json["agentName"],
        type: json["type"],
        userId: json["userId"],
        employeeid: json["employeeid"],
        customerName: json["customerName"],
        count: json["count"],
        cancel: json["cancel"],
        booking: json["booking"],
        hotelname: json["hotelname"],
        hoteltype: json["hoteltype"],
        hotelid: json["hotelid"],
        hotelCategory: json["hotel_category"],
        bookingdate: json["bookingdate"],
        bookingTdy: json["bookingTdy"],
        hotelBookingDtoList: List<HotelBookingDtoList>.from(
            json["hotelBookingDTOList"]
                .map((x) => HotelBookingDtoList.fromJson(x))),
        hotelBookingDto: json["hotelBookingDTO"],
        hotelBookingDtoRebook: json["hotelBookingDTORebook"],
        companyName: json["companyName"],
        address: json["address"],
        mailId: json["mailId"],
        telephone: json["telephone"],
        website: json["website"],
        firstName: json["first_name"],
        middleName: json["middle_name"],
        lastName: json["last_name"],
        age: json["age"],
        nativeCountry: json["native_country"],
        salutaion: json["salutaion"],
        passportNo: json["passport_no"],
        policyDetailsDtoList: json["policyDetailsDTOList"],
        bookingNew: json["bookingNew"],
        hotelIdList: json["hotelIdList"],
        context: json["context"],
        confirmationStatus: json["confirmationStatus"],
        accessCode: json["accessCode"],
        client: json["client"],
        clientrefernce: json["clientrefernce"],
        apiId: json["api_id"],
        supplier: json["supplier"],
        hotelreference: json["hotelreference"],
        hotelName: json["hotel_name"],
        createdBy: json["createdBy"],
        hotelId: json["hotel_id"],
        pending: json["pending"],
        nativeCountryCode: json["native_country_code"],
        packagebookingid: json["packagebookingid"],
        packageBookingCabDto: json["packageBookingCabDTO"],
        availableLimit: json["availableLimit"],
        deleted: json["deleted"],
        refund: json["refund"],
        rebooking: json["rebooking"],
      );

  Map<String, dynamic> toJson() => {
        "booking_id": bookingId,
        "searchlogid": searchlogid,
        "customer_id": customerId,
        "paymentapi_id": paymentapiId,
        "booking_code": bookingCode,
        "voucher_code": voucherCode,
        "booking_confirmation_code": bookingConfirmationCode,
        "common_id": commonId,
        "booking_status": bookingStatus,
        "cancellation_status": cancellationStatus,
        "mail_status": mailStatus,
        "sms_status": smsStatus,
        "remark": remark,
        "booking_date": bookingDate,
        "no_of_pax": noOfPax,
        "total_cost": totalCost,
        "basic_cost": basicCost,
        "profit": profit,
        "discount": discount,
        "dob": dob,
        "agent_id": agentId,
        "employee_id": employeeId,
        "employee": employee,
        "customerDTO": customerDto,
        "hotelBookingDTOArray": hotelBookingDtoArray,
        "emailId": emailId,
        "mobileNumber": mobileNumber,
        "agentName": agentName,
        "type": type,
        "userId": userId,
        "employeeid": employeeid,
        "customerName": customerName,
        "count": count,
        "cancel": cancel,
        "booking": booking,
        "hotelname": hotelname,
        "hoteltype": hoteltype,
        "hotelid": hotelid,
        "hotel_category": hotelCategory,
        "bookingdate": bookingdate,
        "bookingTdy": bookingTdy,
        "hotelBookingDTOList":
            List<dynamic>.from(hotelBookingDtoList.map((x) => x.toJson())),
        "hotelBookingDTO": hotelBookingDto,
        "hotelBookingDTORebook": hotelBookingDtoRebook,
        "companyName": companyName,
        "address": address,
        "mailId": mailId,
        "telephone": telephone,
        "website": website,
        "first_name": firstName,
        "middle_name": middleName,
        "last_name": lastName,
        "age": age,
        "native_country": nativeCountry,
        "salutaion": salutaion,
        "passport_no": passportNo,
        "policyDetailsDTOList": policyDetailsDtoList,
        "bookingNew": bookingNew,
        "hotelIdList": hotelIdList,
        "context": context,
        "confirmationStatus": confirmationStatus,
        "accessCode": accessCode,
        "client": client,
        "clientrefernce": clientrefernce,
        "api_id": apiId,
        "supplier": supplier,
        "hotelreference": hotelreference,
        "hotel_name": hotelName,
        "createdBy": createdBy,
        "hotel_id": hotelId,
        "pending": pending,
        "native_country_code": nativeCountryCode,
        "packagebookingid": packagebookingid,
        "packageBookingCabDTO": packageBookingCabDto,
        "availableLimit": availableLimit,
        "deleted": deleted,
        "refund": refund,
        "rebooking": rebooking,
      };
}

class HotelBookingDtoList {
  dynamic hotelbookingId;
  dynamic bookingId;
  dynamic checkIn;
  dynamic checkOut;
  dynamic bookingDate;
  dynamic hotelId;
  dynamic typeId;
  dynamic type;
  dynamic paymentapiId;
  dynamic currency;
  dynamic currencyValue;
  dynamic paymentStatus;
  dynamic noOfRooms;
  dynamic noOfDays;
  bool cancellationStatus;
  dynamic remark;
  dynamic specialremark;
  dynamic remarkNotes;
  dynamic totalCost;
  dynamic penaltyRateSellingPrice;
  dynamic penaltyRateTotalPrice;
  dynamic client;
  dynamic acesscode;
  dynamic context;
  dynamic apiId;
  dynamic supplier;
  dynamic cancelPen;
  dynamic totalCostWoutmrk;
  dynamic tourismamount;
  dynamic policytotalCost;
  dynamic policytotalCostWthmrk;
  dynamic mealPlanId;
  dynamic commonId;
  dynamic agentId;
  dynamic employeeId;
  dynamic hotelbookingapiId;
  dynamic nativeCountryId;
  dynamic totpax;
  dynamic cancelDate;
  dynamic paramsBooking;
  dynamic hotelRoomBookingDtoArray;
  dynamic eachDayRatesDtoList;
  dynamic hotelIncludesBookingDtoArray;
  dynamic hotelBookingPromotionsDtoArray;
  dynamic discountPromotionsDto;
  dynamic staypayPromotionsDto;
  dynamic specialPromotionsDto;
  dynamic monthlylPromotionsDto;
  dynamic hotelBookingDayRatesDtOs;
  dynamic invoiceNo;
  dynamic checkInText;
  dynamic checkOutText;
  dynamic bookTime;
  dynamic amendTime;
  dynamic cancelTime;
  dynamic bookingCode;
  dynamic checkInCnt;
  dynamic checkOutCnt;
  dynamic hotelname;
  dynamic agentname;
  dynamic hoteltype;
  dynamic rcname;
  dynamic customername;
  dynamic clientrefernce;
  dynamic inhouserefernce;
  dynamic pricerefernce;
  dynamic hotelrefernce;
  dynamic apistatus;
  dynamic confirmationStatus;
  dynamic onHoldStatus;
  dynamic hotelCategory;
  dynamic location;
  dynamic dateDiff;
  List<HotelRoomBookingDtoList> hotelRoomBookingDtoList;
  dynamic hotelRoomListRebook;
  List<dynamic> policyDetailsDtoList;
  List<dynamic> mailList;
  List<dynamic> hotelTermsAndConditionsDtoList;
  dynamic cost;
  dynamic hotelcost;
  dynamic userId;
  dynamic costnights;
  dynamic hotelcostnights;
  dynamic availableLimit;
  dynamic creditlimit;
  dynamic used;
  dynamic taxNo;
  dynamic policyId;
  dynamic avaiRooms;
  dynamic tourismDirhams;
  dynamic valuePercent;
  dynamic policyType;
  dynamic policydetailsId;
  dynamic fname;
  dynamic mname;
  dynamic salutation;
  dynamic lname;
  dynamic createdBy;
  dynamic childAge;
  dynamic resNo;
  dynamic hotelBookId;
  dynamic searchRoomDto;
  dynamic paramsBookingws;
  dynamic internalcode;
  dynamic packagebookingid;
  bool deleted;
  bool refund;
  bool rebook;

  HotelBookingDtoList({
    required this.hotelbookingId,
    required this.bookingId,
    required this.checkIn,
    required this.checkOut,
    required this.bookingDate,
    required this.hotelId,
    required this.typeId,
    required this.type,
    required this.paymentapiId,
    required this.currency,
    required this.currencyValue,
    required this.paymentStatus,
    required this.noOfRooms,
    required this.noOfDays,
    required this.cancellationStatus,
    required this.remark,
    required this.specialremark,
    required this.remarkNotes,
    required this.totalCost,
    required this.penaltyRateSellingPrice,
    required this.penaltyRateTotalPrice,
    required this.client,
    required this.acesscode,
    required this.context,
    required this.apiId,
    required this.supplier,
    required this.cancelPen,
    required this.totalCostWoutmrk,
    required this.tourismamount,
    required this.policytotalCost,
    required this.policytotalCostWthmrk,
    required this.mealPlanId,
    required this.commonId,
    required this.agentId,
    required this.employeeId,
    required this.hotelbookingapiId,
    required this.nativeCountryId,
    required this.totpax,
    required this.cancelDate,
    required this.paramsBooking,
    required this.hotelRoomBookingDtoArray,
    required this.eachDayRatesDtoList,
    required this.hotelIncludesBookingDtoArray,
    required this.hotelBookingPromotionsDtoArray,
    required this.discountPromotionsDto,
    required this.staypayPromotionsDto,
    required this.specialPromotionsDto,
    required this.monthlylPromotionsDto,
    required this.hotelBookingDayRatesDtOs,
    required this.invoiceNo,
    required this.checkInText,
    required this.checkOutText,
    required this.bookTime,
    required this.amendTime,
    required this.cancelTime,
    required this.bookingCode,
    required this.checkInCnt,
    required this.checkOutCnt,
    required this.hotelname,
    required this.agentname,
    required this.hoteltype,
    required this.rcname,
    required this.customername,
    required this.clientrefernce,
    required this.inhouserefernce,
    required this.pricerefernce,
    required this.hotelrefernce,
    required this.apistatus,
    required this.confirmationStatus,
    required this.onHoldStatus,
    required this.hotelCategory,
    required this.location,
    required this.dateDiff,
    required this.hotelRoomBookingDtoList,
    required this.hotelRoomListRebook,
    required this.policyDetailsDtoList,
    required this.mailList,
    required this.hotelTermsAndConditionsDtoList,
    required this.cost,
    required this.hotelcost,
    required this.userId,
    required this.costnights,
    required this.hotelcostnights,
    required this.availableLimit,
    required this.creditlimit,
    required this.used,
    required this.taxNo,
    required this.policyId,
    required this.avaiRooms,
    required this.tourismDirhams,
    required this.valuePercent,
    required this.policyType,
    required this.policydetailsId,
    required this.fname,
    required this.mname,
    required this.salutation,
    required this.lname,
    required this.createdBy,
    required this.childAge,
    required this.resNo,
    required this.hotelBookId,
    required this.searchRoomDto,
    required this.paramsBookingws,
    required this.internalcode,
    required this.packagebookingid,
    required this.deleted,
    required this.refund,
    required this.rebook,
  });

  factory HotelBookingDtoList.fromJson(Map<String, dynamic> json) =>
      HotelBookingDtoList(
        hotelbookingId: json["hotelbooking_id"],
        bookingId: json["booking_id"],
        checkIn: json["check_in"],
        checkOut: json["check_out"],
        bookingDate: json["booking_date"],
        hotelId: json["hotel_id"],
        typeId: json["type_id"],
        type: json["type"],
        paymentapiId: json["paymentapi_id"],
        currency: json["currency"],
        currencyValue: json["currencyValue"],
        paymentStatus: json["paymentStatus"],
        noOfRooms: json["no_of_rooms"],
        noOfDays: json["no_of_days"],
        cancellationStatus: json["cancellation_status"],
        remark: json["remark"],
        specialremark: json["specialremark"],
        remarkNotes: json["remarkNotes"],
        totalCost: json["total_cost"],
        penaltyRateSellingPrice: json["penaltyRateSellingPrice"],
        penaltyRateTotalPrice: json["penaltyRateTotalPrice"],
        client: json["client"],
        acesscode: json["acesscode"],
        context: json["context"],
        apiId: json["api_id"],
        supplier: json["supplier"],
        cancelPen: json["cancelPen"],
        totalCostWoutmrk: json["total_cost_woutmrk"],
        tourismamount: json["tourismamount"],
        policytotalCost: json["policytotal_cost"],
        policytotalCostWthmrk: json["policytotal_cost_wthmrk"],
        mealPlanId: json["meal_plan_id"],
        commonId: json["common_id"],
        agentId: json["agent_id"],
        employeeId: json["employee_id"],
        hotelbookingapiId: json["hotelbookingapi_id"],
        nativeCountryId: json["native_country_id"],
        totpax: json["totpax"],
        cancelDate: json["cancelDate"],
        paramsBooking: json["paramsBooking"],
        hotelRoomBookingDtoArray: json["hotelRoomBookingDTOArray"],
        eachDayRatesDtoList: json["eachDayRatesDTOList"],
        hotelIncludesBookingDtoArray: json["hotelIncludesBookingDTOArray"],
        hotelBookingPromotionsDtoArray: json["hotelBookingPromotionsDTOArray"],
        discountPromotionsDto: json["discountPromotionsDTO"],
        staypayPromotionsDto: json["staypayPromotionsDTO"],
        specialPromotionsDto: json["specialPromotionsDTO"],
        monthlylPromotionsDto: json["monthlylPromotionsDTO"],
        hotelBookingDayRatesDtOs: json["hotelBookingDayRatesDTOs"],
        invoiceNo: json["invoice_no"],
        checkInText: json["check_in_text"],
        checkOutText: json["check_out_text"],
        bookTime: json["bookTime"],
        amendTime: json["amendTime"],
        cancelTime: json["cancelTime"],
        bookingCode: json["booking_code"],
        checkInCnt: json["checkInCnt"],
        checkOutCnt: json["checkOutCnt"],
        hotelname: json["hotelname"],
        agentname: json["agentname"],
        hoteltype: json["hoteltype"],
        rcname: json["rcname"],
        customername: json["customername"],
        clientrefernce: json["clientrefernce"],
        inhouserefernce: json["inhouserefernce"],
        pricerefernce: json["pricerefernce"],
        hotelrefernce: json["hotelrefernce"],
        apistatus: json["apistatus"],
        confirmationStatus: json["confirmationStatus"],
        onHoldStatus: json["onHoldStatus"],
        hotelCategory: json["hotel_category"],
        location: json["location"],
        dateDiff: json["dateDiff"],
        hotelRoomBookingDtoList: List<HotelRoomBookingDtoList>.from(
            json["hotelRoomBookingDTOList"]
                .map((x) => HotelRoomBookingDtoList.fromJson(x))),
        hotelRoomListRebook: json["hotelRoomListRebook"],
        policyDetailsDtoList:
            List<dynamic>.from(json["policyDetailsDTOList"].map((x) => x)),
        mailList: List<dynamic>.from(json["mailList"].map((x) => x)),
        hotelTermsAndConditionsDtoList: List<dynamic>.from(
            json["hotelTermsAndConditionsDTOList"].map((x) => x)),
        cost: json["cost"],
        hotelcost: json["hotelcost"],
        userId: json["userId"],
        costnights: json["costnights"],
        hotelcostnights: json["hotelcostnights"],
        availableLimit: json["availableLimit"],
        creditlimit: json["creditlimit"],
        used: json["used"],
        taxNo: json["tax_no"],
        policyId: json["policy_id"],
        avaiRooms: json["avai_rooms"],
        tourismDirhams: json["tourism_dirhams"],
        valuePercent: json["valuePercent"],
        policyType: json["policyType"],
        policydetailsId: json["policydetails_id"],
        fname: json["fname"],
        mname: json["mname"],
        salutation: json["salutation"],
        lname: json["lname"],
        createdBy: json["createdBy"],
        childAge: json["childAge"],
        resNo: json["resNo"],
        hotelBookId: json["hotelBookId"],
        searchRoomDto: json["searchRoomDTO"],
        paramsBookingws: json["paramsBookingws"],
        internalcode: json["internalcode"],
        packagebookingid: json["packagebookingid"],
        deleted: json["deleted"],
        refund: json["refund"],
        rebook: json["rebook"],
      );

  Map<String, dynamic> toJson() => {
        "hotelbooking_id": hotelbookingId,
        "booking_id": bookingId,
        "check_in": checkIn,
        "check_out": checkOut,
        "booking_date": bookingDate,
        "hotel_id": hotelId,
        "type_id": typeId,
        "type": type,
        "paymentapi_id": paymentapiId,
        "currency": currency,
        "currencyValue": currencyValue,
        "paymentStatus": paymentStatus,
        "no_of_rooms": noOfRooms,
        "no_of_days": noOfDays,
        "cancellation_status": cancellationStatus,
        "remark": remark,
        "specialremark": specialremark,
        "remarkNotes": remarkNotes,
        "total_cost": totalCost,
        "penaltyRateSellingPrice": penaltyRateSellingPrice,
        "penaltyRateTotalPrice": penaltyRateTotalPrice,
        "client": client,
        "acesscode": acesscode,
        "context": context,
        "api_id": apiId,
        "supplier": supplier,
        "cancelPen": cancelPen,
        "total_cost_woutmrk": totalCostWoutmrk,
        "tourismamount": tourismamount,
        "policytotal_cost": policytotalCost,
        "policytotal_cost_wthmrk": policytotalCostWthmrk,
        "meal_plan_id": mealPlanId,
        "common_id": commonId,
        "agent_id": agentId,
        "employee_id": employeeId,
        "hotelbookingapi_id": hotelbookingapiId,
        "native_country_id": nativeCountryId,
        "totpax": totpax,
        "cancelDate": cancelDate,
        "paramsBooking": paramsBooking,
        "hotelRoomBookingDTOArray": hotelRoomBookingDtoArray,
        "eachDayRatesDTOList": eachDayRatesDtoList,
        "hotelIncludesBookingDTOArray": hotelIncludesBookingDtoArray,
        "hotelBookingPromotionsDTOArray": hotelBookingPromotionsDtoArray,
        "discountPromotionsDTO": discountPromotionsDto,
        "staypayPromotionsDTO": staypayPromotionsDto,
        "specialPromotionsDTO": specialPromotionsDto,
        "monthlylPromotionsDTO": monthlylPromotionsDto,
        "hotelBookingDayRatesDTOs": hotelBookingDayRatesDtOs,
        "invoice_no": invoiceNo,
        "check_in_text": checkInText,
        "check_out_text": checkOutText,
        "bookTime": bookTime,
        "amendTime": amendTime,
        "cancelTime": cancelTime,
        "booking_code": bookingCode,
        "checkInCnt": checkInCnt,
        "checkOutCnt": checkOutCnt,
        "hotelname": hotelname,
        "agentname": agentname,
        "hoteltype": hoteltype,
        "rcname": rcname,
        "customername": customername,
        "clientrefernce": clientrefernce,
        "inhouserefernce": inhouserefernce,
        "pricerefernce": pricerefernce,
        "hotelrefernce": hotelrefernce,
        "apistatus": apistatus,
        "confirmationStatus": confirmationStatus,
        "onHoldStatus": onHoldStatus,
        "hotel_category": hotelCategory,
        "location": location,
        "dateDiff": dateDiff,
        "hotelRoomBookingDTOList":
            List<dynamic>.from(hotelRoomBookingDtoList.map((x) => x.toJson())),
        "hotelRoomListRebook": hotelRoomListRebook,
        "policyDetailsDTOList":
            List<dynamic>.from(policyDetailsDtoList.map((x) => x)),
        "mailList": List<dynamic>.from(mailList.map((x) => x)),
        "hotelTermsAndConditionsDTOList":
            List<dynamic>.from(hotelTermsAndConditionsDtoList.map((x) => x)),
        "cost": cost,
        "hotelcost": hotelcost,
        "userId": userId,
        "costnights": costnights,
        "hotelcostnights": hotelcostnights,
        "availableLimit": availableLimit,
        "creditlimit": creditlimit,
        "used": used,
        "tax_no": taxNo,
        "policy_id": policyId,
        "avai_rooms": avaiRooms,
        "tourism_dirhams": tourismDirhams,
        "valuePercent": valuePercent,
        "policyType": policyType,
        "policydetails_id": policydetailsId,
        "fname": fname,
        "mname": mname,
        "salutation": salutation,
        "lname": lname,
        "createdBy": createdBy,
        "childAge": childAge,
        "resNo": resNo,
        "hotelBookId": hotelBookId,
        "searchRoomDTO": searchRoomDto,
        "paramsBookingws": paramsBookingws,
        "internalcode": internalcode,
        "packagebookingid": packagebookingid,
        "deleted": deleted,
        "refund": refund,
        "rebook": rebook,
      };
}

class HotelRoomBookingDtoList {
  dynamic checkIn;
  dynamic checkOut;
  dynamic bookingRoomId;
  dynamic hotelBookingId;
  dynamic roomCatId;
  bool isRefund;
  dynamic shareTypeId;
  dynamic shareTypeIdapi;
  dynamic refundstr;
  dynamic noOfAdult;
  dynamic noOfChild;
  dynamic mealPlanId;
  dynamic totalCost;
  dynamic totalCostWrtmarkup;
  dynamic childAge;
  dynamic contrateRateIds;
  dynamic specialRateIds;
  dynamic monthlyRateIds;
  dynamic totalCostWoutMark;
  dynamic createdDate;
  dynamic modifiedDate;
  dynamic createdBy;
  dynamic modifiedBy;
  dynamic agentId;
  dynamic employeeId;
  dynamic hotelId;
  dynamic nativeCountryId;
  dynamic mealPlanArray;
  dynamic childAgeArray;
  dynamic roomCategoryName;
  dynamic mealPlanName;
  dynamic roomtypeName;
  dynamic supplements;
  dynamic occuptypeName;
  dynamic occupancyTypeId;
  List<dynamic> hotelMealPlanBookingDtoList;
  dynamic compulList;
  dynamic rateCompulsoryIncludesDtoList;
  dynamic eachDayBookingDto;
  dynamic bookingRateDtoList;
  dynamic roomBookingDayRatesDtOs;
  dynamic hotelCompulsoryBookingDtOs;
  dynamic noOfInfant;
  dynamic promoId;
  dynamic promoType;
  dynamic noOfRooms;
  dynamic costWthoutMrkp;
  dynamic noOfAdultExtra;
  dynamic noOfChildExtra;
  dynamic type;
  dynamic agentCurr;
  dynamic userId;
  dynamic shareTypeIdapiWs;
  dynamic price;
  dynamic bftype;
  dynamic hotelRoomBookingDtoListRoomCategoryName;
  dynamic roomCategoryId;
  dynamic hBookId;
  dynamic resNo;
  dynamic hotelIdWs;
  dynamic apiStatus;
  dynamic internalCode;
  List<dynamic> guestdetailsDtoArray;
  bool status;
  bool deleted;
  bool refund;

  HotelRoomBookingDtoList({
    required this.checkIn,
    required this.checkOut,
    required this.bookingRoomId,
    required this.hotelBookingId,
    required this.roomCatId,
    required this.isRefund,
    required this.shareTypeId,
    required this.shareTypeIdapi,
    required this.refundstr,
    required this.noOfAdult,
    required this.noOfChild,
    required this.mealPlanId,
    required this.totalCost,
    required this.totalCostWrtmarkup,
    required this.childAge,
    required this.contrateRateIds,
    required this.specialRateIds,
    required this.monthlyRateIds,
    required this.totalCostWoutMark,
    required this.createdDate,
    required this.modifiedDate,
    required this.createdBy,
    required this.modifiedBy,
    required this.agentId,
    required this.employeeId,
    required this.hotelId,
    required this.nativeCountryId,
    required this.mealPlanArray,
    required this.childAgeArray,
    required this.roomCategoryName,
    required this.mealPlanName,
    required this.roomtypeName,
    required this.supplements,
    required this.occuptypeName,
    required this.occupancyTypeId,
    required this.hotelMealPlanBookingDtoList,
    required this.compulList,
    required this.rateCompulsoryIncludesDtoList,
    required this.eachDayBookingDto,
    required this.bookingRateDtoList,
    required this.roomBookingDayRatesDtOs,
    required this.hotelCompulsoryBookingDtOs,
    required this.noOfInfant,
    required this.promoId,
    required this.promoType,
    required this.noOfRooms,
    required this.costWthoutMrkp,
    required this.noOfAdultExtra,
    required this.noOfChildExtra,
    required this.type,
    required this.agentCurr,
    required this.userId,
    required this.shareTypeIdapiWs,
    required this.price,
    required this.bftype,
    required this.hotelRoomBookingDtoListRoomCategoryName,
    required this.roomCategoryId,
    required this.hBookId,
    required this.resNo,
    required this.hotelIdWs,
    required this.apiStatus,
    required this.internalCode,
    required this.guestdetailsDtoArray,
    required this.status,
    required this.deleted,
    required this.refund,
  });

  factory HotelRoomBookingDtoList.fromJson(Map<String, dynamic> json) =>
      HotelRoomBookingDtoList(
        checkIn: json["check_in"],
        checkOut: json["check_out"],
        bookingRoomId: json["booking_room_id"],
        hotelBookingId: json["hotel_booking_id"],
        roomCatId: json["room_cat_id"],
        isRefund: json["isRefund"],
        shareTypeId: json["share_type_id"],
        shareTypeIdapi: json["share_type_idapi"],
        refundstr: json["refundstr"],
        noOfAdult: json["no_of_adult"],
        noOfChild: json["no_of_child"],
        mealPlanId: json["meal_plan_id"],
        totalCost: json["total_cost"],
        totalCostWrtmarkup: json["total_cost_wrtmarkup"],
        childAge: json["childAge"],
        contrateRateIds: json["contrateRateIds"],
        specialRateIds: json["specialRateIds"],
        monthlyRateIds: json["monthlyRateIds"],
        totalCostWoutMark: json["total_cost_wout_mark"],
        createdDate: json["createdDate"],
        modifiedDate: json["modifiedDate"],
        createdBy: json["createdBy"],
        modifiedBy: json["modifiedBy"],
        agentId: json["agent_id"],
        employeeId: json["employee_id"],
        hotelId: json["hotel_id"],
        nativeCountryId: json["native_country_id"],
        mealPlanArray: json["meal_plan_Array"],
        childAgeArray: json["childAge_Array"],
        roomCategoryName: json["roomCategoryName"],
        mealPlanName: json["mealPlanName"],
        roomtypeName: json["roomtypeName"],
        supplements: json["supplements"],
        occuptypeName: json["occuptypeName"],
        occupancyTypeId: json["occupancy_Type_id"],
        hotelMealPlanBookingDtoList: List<dynamic>.from(
            json["hotelMealPlanBookingDTOList"].map((x) => x)),
        compulList: json["compulList"],
        rateCompulsoryIncludesDtoList: json["rateCompulsoryIncludesDTOList"],
        eachDayBookingDto: json["eachDayBookingDTO"],
        bookingRateDtoList: json["bookingRateDTOList"],
        roomBookingDayRatesDtOs: json["roomBookingDayRatesDTOs"],
        hotelCompulsoryBookingDtOs: json["hotelCompulsoryBookingDTOs"],
        noOfInfant: json["no_of_infant"],
        promoId: json["promo_id"],
        promoType: json["promo_type"],
        noOfRooms: json["no_of_rooms"],
        costWthoutMrkp: json["cost_wthout_mrkp"],
        noOfAdultExtra: json["no_of_adult_extra"],
        noOfChildExtra: json["no_of_child_extra"],
        type: json["type"],
        agentCurr: json["agent_curr"],
        userId: json["userId"],
        shareTypeIdapiWs: json["share_type_idapi_ws"],
        price: json["price"],
        bftype: json["bftype"],
        hotelRoomBookingDtoListRoomCategoryName: json["room_category_name"],
        roomCategoryId: json["room_category_id"],
        hBookId: json["hBookId"],
        resNo: json["resNo"],
        hotelIdWs: json["hotel_id_ws"],
        apiStatus: json["apiStatus"],
        internalCode: json["internal_code"],
        guestdetailsDtoArray:
            List<dynamic>.from(json["guestdetailsDTOArray"].map((x) => x)),
        status: json["status"],
        deleted: json["deleted"],
        refund: json["refund"],
      );

  Map<String, dynamic> toJson() => {
        "check_in": checkIn,
        "check_out": checkOut,
        "booking_room_id": bookingRoomId,
        "hotel_booking_id": hotelBookingId,
        "room_cat_id": roomCatId,
        "isRefund": isRefund,
        "share_type_id": shareTypeId,
        "share_type_idapi": shareTypeIdapi,
        "refundstr": refundstr,
        "no_of_adult": noOfAdult,
        "no_of_child": noOfChild,
        "meal_plan_id": mealPlanId,
        "total_cost": totalCost,
        "total_cost_wrtmarkup": totalCostWrtmarkup,
        "childAge": childAge,
        "contrateRateIds": contrateRateIds,
        "specialRateIds": specialRateIds,
        "monthlyRateIds": monthlyRateIds,
        "total_cost_wout_mark": totalCostWoutMark,
        "createdDate": createdDate,
        "modifiedDate": modifiedDate,
        "createdBy": createdBy,
        "modifiedBy": modifiedBy,
        "agent_id": agentId,
        "employee_id": employeeId,
        "hotel_id": hotelId,
        "native_country_id": nativeCountryId,
        "meal_plan_Array": mealPlanArray,
        "childAge_Array": childAgeArray,
        "roomCategoryName": roomCategoryName,
        "mealPlanName": mealPlanName,
        "roomtypeName": roomtypeName,
        "supplements": supplements,
        "occuptypeName": occuptypeName,
        "occupancy_Type_id": occupancyTypeId,
        "hotelMealPlanBookingDTOList":
            List<dynamic>.from(hotelMealPlanBookingDtoList.map((x) => x)),
        "compulList": compulList,
        "rateCompulsoryIncludesDTOList": rateCompulsoryIncludesDtoList,
        "eachDayBookingDTO": eachDayBookingDto,
        "bookingRateDTOList": bookingRateDtoList,
        "roomBookingDayRatesDTOs": roomBookingDayRatesDtOs,
        "hotelCompulsoryBookingDTOs": hotelCompulsoryBookingDtOs,
        "no_of_infant": noOfInfant,
        "promo_id": promoId,
        "promo_type": promoType,
        "no_of_rooms": noOfRooms,
        "cost_wthout_mrkp": costWthoutMrkp,
        "no_of_adult_extra": noOfAdultExtra,
        "no_of_child_extra": noOfChildExtra,
        "type": type,
        "agent_curr": agentCurr,
        "userId": userId,
        "share_type_idapi_ws": shareTypeIdapiWs,
        "price": price,
        "bftype": bftype,
        "room_category_name": hotelRoomBookingDtoListRoomCategoryName,
        "room_category_id": roomCategoryId,
        "hBookId": hBookId,
        "resNo": resNo,
        "hotel_id_ws": hotelIdWs,
        "apiStatus": apiStatus,
        "internal_code": internalCode,
        "guestdetailsDTOArray":
            List<dynamic>.from(guestdetailsDtoArray.map((x) => x)),
        "status": status,
        "deleted": deleted,
        "refund": refund,
      };
}
